ch015(비모수적 검정)
================
jakinpilla
2020-02-06

  - [비모수적 검정은 언제 사용할까?](#비모수적-검정은-언제-사용할까)
  - [독립적인 두 조건의 비교: 윌콕스 순위합 검정](#독립적인-두-조건의-비교-윌콕스-순위합-검정)
  - [윌콕슨 순위합 검정의 이론](#윌콕슨-순위합-검정의-이론)
  - [자료 입력과 잠정 분석](#자료-입력과-잠정-분석)
  - [R을 이용한 윌콕슨 순위합 검정 실행](#r을-이용한-윌콕슨-순위합-검정-실행)
  - [효과크기 계산](#효과크기-계산)
  - [윌콕슨 순위합 검정 결과의 보고](#윌콕슨-순위합-검정-결과의-보고)

#### 비모수적 검정은 언제 사용할까?

ranking 순위화에 기초

``` r
library(ez)
library(ggplot2)
library(nlme)
library(pastecs)
library(reshape2)
library(WRS)
library(clinfun)
library(pgirmess)
library(car)
library(tidyverse)
```

#### 독립적인 두 조건의 비교: 윌콕스 순위합 검정

Mann-Whitney test

Wilcoxon’s rank-sum test

#### 윌콕슨 순위합 검정의 이론

평균순위 : 1에서 그룹 크기까지의 합

  
![ meanRank = \\frac{N(N+1)}{2}
](https://latex.codecogs.com/png.latex?%20meanRank%20%3D%20%5Cfrac%7BN%28N%2B1%29%7D%7B2%7D%20
" meanRank = \\frac{N(N+1)}{2} ")  

  
![ W = rankSum - meanRank
](https://latex.codecogs.com/png.latex?%20W%20%3D%20rankSum%20-%20meanRank%20
" W = rankSum - meanRank ")  

W : 검정통계량, p-value, 참값 접근 방식, 정규 근사 접근방식식

참값 접근 방식은 몬테카를로 방법을 이용해서 유의수준을 구한다. 몬테카를로 방법은 표본과 부합하는 다수의 부분집합을 생성하되,
참가자들을 정확한 그룹에 넣는 것이 아니라 무작위로 선택한 그룹에 넣는다. 참가자들이 무작위로 그룹에 배정되므로 귀무가설이
참이다. 따라서, 귀무가설이 참인 자료에 기초해서 W값을 계산하면 된다.

R은 사람들을 무작위로 배정해서 한 번만 분석하는 것이 아니라 그러한 과정을 수천번 반복하면서 귀무가설이 참일 때 나타나는 차이가
여러분의 자료에 나타난 차이만큼 큰 경우의 횟수를 센다.

또다른 계산 방법은 정규 근사 접근 방식이다. W 통계량의 표집분포가 정규분포라고 가정한다. 그 가정이 성립한다면 z 값을
계산하는데 쓰이는 표준오차를 구할 수 있으며 따라서 p 값도 구할 수 있다. R은 기본적으로 표본크기가 40을
넘으면 정규 근사 접근 방식을 사용한다. 그리고 자료에 동순위 점수들이 있으면 좋든 싫든 정규 근사 접근 방식을
사용해야 한다.

정규 근사 접근 방식으로 p 값을 계산할 때는 필요하다면 연속성 수정을 가할 수도 있다. R의 경우 따로 특별히 지정하지 않으면
연속성 수정을 가한다.

#### 자료 입력과 잠정 분석

``` r
gl(2, 10, labels = c('Ecstacy', 'Alcohol'))
```

    ##  [1] Ecstacy Ecstacy Ecstacy Ecstacy Ecstacy Ecstacy Ecstacy Ecstacy
    ##  [9] Ecstacy Ecstacy Alcohol Alcohol Alcohol Alcohol Alcohol Alcohol
    ## [17] Alcohol Alcohol Alcohol Alcohol
    ## Levels: Ecstacy Alcohol

``` r
drugData <- read.delim('Drug.dat',  header = T)

drugData
```

    ##       drug sundayBDI wedsBDI
    ## 1  Ecstasy        15      28
    ## 2  Ecstasy        35      35
    ## 3  Ecstasy        16      35
    ## 4  Ecstasy        18      24
    ## 5  Ecstasy        19      39
    ## 6  Ecstasy        17      32
    ## 7  Ecstasy        27      27
    ## 8  Ecstasy        16      29
    ## 9  Ecstasy        13      36
    ## 10 Ecstasy        20      35
    ## 11 Alcohol        16       5
    ## 12 Alcohol        15       6
    ## 13 Alcohol        20      30
    ## 14 Alcohol        15       8
    ## 15 Alcohol        16       9
    ## 16 Alcohol        13       7
    ## 17 Alcohol        14       6
    ## 18 Alcohol        19      17
    ## 19 Alcohol        18       3
    ## 20 Alcohol        18      10

자가진단

이 자료들의 정규성 가정과 분산의 동질성 가정을 점검하라.

``` r
by(drugData[,c(2:3)], drugData$drug, stat.desc, basic=FALSE, norm=TRUE)
```

    ## drugData$drug: Alcohol
    ##                sundayBDI      wedsBDI
    ## median       16.00000000  7.500000000
    ## mean         16.40000000 10.100000000
    ## SE.mean       0.71802197  2.514181996
    ## CI.mean.0.95  1.62427855  5.687474812
    ## var           5.15555556 63.211111111
    ## std.dev       2.27058485  7.950541561
    ## coef.var      0.13845030  0.787182333
    ## skewness      0.11686189  1.500374383
    ## skew.2SE      0.08504701  1.091907319
    ## kurtosis     -1.49015904  1.079109997
    ## kurt.2SE     -0.55842624  0.404388605
    ## normtest.W    0.95946584  0.753466511
    ## normtest.p    0.77976459  0.003933024
    ## -------------------------------------------------------- 
    ## drugData$drug: Ecstasy
    ##                sundayBDI    wedsBDI
    ## median       17.50000000 33.5000000
    ## mean         19.60000000 32.0000000
    ## SE.mean       2.08806130  1.5129074
    ## CI.mean.0.95  4.72352283  3.4224344
    ## var          43.60000000 22.8888889
    ## std.dev       6.60302961  4.7842334
    ## coef.var      0.33688927  0.1495073
    ## skewness      1.23571300 -0.2191665
    ## skew.2SE      0.89929826 -0.1594999
    ## kurtosis      0.26030385 -1.4810114
    ## kurt.2SE      0.09754697 -0.5549982
    ## normtest.W    0.81063991  0.9411413
    ## normtest.p    0.01952060  0.5657814

일요일, 알코올의 경우 W= .96, 유의하지 않음 이므로 정규성을 가짐

일요일, 엑스터시의 경우 W = .81, 유의함 이므로 정규분포가 아님

수요일, 알코올의 경우 W = .75, 유의함이므로 정규분초가 아님

수요일, 엑스터시의 경우 W = .94, 유의하지 않음 이므로 정규성을 가짐

일요일 자료와 수요일 자료의 표집분포도 정규분포가 아닐 수 있다. 그러므로 비모수적 검정을 사용한다.

``` r
leveneTest(drugData$sundayBDI, drugData$drug, center = "mean")
```

    ## Levene's Test for Homogeneity of Variance (center = "mean")
    ##       Df F value  Pr(>F)  
    ## group  1  3.6436 0.07236 .
    ##       18                  
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

``` r
leveneTest(drugData$wedsBDI, drugData$drug, center = "mean")
```

    ## Levene's Test for Homogeneity of Variance (center = "mean")
    ##       Df F value Pr(>F)
    ## group  1  0.5081 0.4851
    ##       18

모두 유의하지 않으므로 분산의 동질성 가정이 성립한다.

``` r
# install.packages('Rcmdr', dependencies = T)
# library(Rcmdr)
```

Rcmdr를 사용하면 자료에 동순위 점수들이 있으면 참값 접근 방식을 사용할 수 없다는 점과 표분 크기가 크면 오랜 시간이
걸린다는 점은 명심하자.

#### R을 이용한 윌콕슨 순위합 검정 실행

``` r
sunModel <- wilcox.test(sundayBDI ~ drug, data = drugData); sunModel
```

    ## Warning in wilcox.test.default(x = c(16L, 15L, 20L, 15L, 16L, 13L, 14L, :
    ## cannot compute exact p-value with ties

    ## 
    ##  Wilcoxon rank sum test with continuity correction
    ## 
    ## data:  sundayBDI by drug
    ## W = 35.5, p-value = 0.2861
    ## alternative hypothesis: true location shift is not equal to 0

``` r
wedModel <- wilcox.test(wedsBDI ~ drug, data = drugData); wedModel
```

    ## Warning in wilcox.test.default(x = c(5L, 6L, 30L, 8L, 9L, 7L, 6L, 17L,
    ## 3L, : cannot compute exact p-value with ties

    ## 
    ##  Wilcoxon rank sum test with continuity correction
    ## 
    ## data:  wedsBDI by drug
    ## W = 4, p-value = 0.000569
    ## alternative hypothesis: true location shift is not equal to 0

Warning in wilcox.test.default(x = c(16L, 15L, 20L, 15L, 16L, 13L, 14L,
:cannot compute exact p-value with ties

기본 설정인 참값 접근 방식을 요구했지만, 동순위 점수들이 있어 그 접근방식을 사용할 수 없었다는 의미이다.

#### 효과크기 계산

나만의 윌콕슨 순위합 검정

``` r
library(dplyr)
drugData %>% 
  filter(drug == 'Alcohol') %>% 
  dplyr::select(sundayBDI) %>%
  pull(sundayBDI) -> g1


drugData %>% 
  filter(drug == 'Ecstasy') %>% 
  dplyr::select(sundayBDI) %>%
  pull(sundayBDI) -> g2

n1 <- length(g1)
n2 <- length(g2)

w <- rank(c(g1, g2))
r1 <- w[1:n1]
r2 <- w[(n1+1):(n1+n2)]

w1 <- sum(r1)
w2 <- sum(r2)

wilc1 <- w1 - n1*(n1+1)/2
wilc2 <- w2 - n2*(n2+1)/2

wilc <- min(wilc1, wilc2)
wilc
```

    ## [1] 35.5

``` r
m1 <- mean(r1)
m2 <- mean(r2)

m1
```

    ## [1] 9.05

``` r
m2
```

    ## [1] 11.95

효과크기를 계산하는 함수를 제작한다.

``` r
rFormWilcox <- function(wilcoxModel, N) {
  z <- qnorm(wilcoxModel$p.value/2)
  r <- z / sqrt(N)
  
  cat(wilcoxModel$data.name, 'Effect Size, r = ', r)
}
```

각 모델에 대해 이 함수를 사용한다.

``` r
rFormWilcox(sunModel, 20) 
```

    ## sundayBDI by drug Effect Size, r =  -0.2385338

``` r
rFormWilcox(wedModel, 20)
```

    ## wedsBDI by drug Effect Size, r =  -0.7705401

일요일 자료의 효과크기는 작은 효과와 중간 효과의 사이이고(.3보다 작다) 수요일 자료의 효과크기는 아주 큰 효과에 해당한다.(큰
효과의 기준 .5보다 크다.)

#### 윌콕슨 순위합 검정 결과의 보고

약물 복용 다음 날(일요일)의 엑스터시 복용자의 우울증 수준(Mdn = 17.50)과 알코올 복용자의 우울증 수준(Mdn =
16.00)의 차이는 W = 35.5, p = .286, r = -.25로 유의하지 않았다. 그러나 주중(수요일)의 엑스터시
복용자의 우울증 수준(Mdn = 33.50)과 알코올 복용자의 우울증 수준(Mdn = 7.50)의 차이는 W = 4,
p \< .001, r = -.78 로 유의했다.
